name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

#    - uses: actions/checkout@v2
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }/bug_master_bot:$(date +%s)
#
#    - uses: actions/checkout@v2
#    - name: Docker push
#      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bug_master_bot